baseURL = 'https://starrynightrp.netlify.app/'
languageCode = 'en-us'
title = 'Fate/Starry Night'
theme = ['hugo-book-nat', 'hugo-shortcode-roneo-collection']

[params]
images = ["img/og-image.jpg"]
BookTheme = 'dark'

# (Optional, default none) Set leaf bundle to render as side menu
# When not specified file structure and weights will be used
#BookMenuBundle = '/menu'
BookMenuBundle = ''
BookSection='/lore'
BookToC = 'true'

[markup]
[markup.tableOfContents]
  startLevel = 1