backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img # Folder where user uploaded files should go
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: 'home' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Home' # Used in the UI, ie.: "New Post"
    label_singular: 'Home Page'
    folder: 'content/lore/0-home' # The path to the folder where the documents are stored
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: true
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Intro Blurb", name: "description", widget: "text"} # new
      - {label: "Image", name: "image", widget: "image", required: false} # new
      - { label: 'File', name: 'file', widget: 'file', required: false} # new
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'introduction' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Introduction' # Used in the UI, ie.: "New Post"
    label_singular: 'Introduction Page'
    folder: 'content/lore/1-introduction' # The path to the folder where the documents are stored
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: true
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Intro Blurb", name: "description", widget: "text"} # new
      - {label: "Image", name: "image", widget: "image", required: false} # new
      - { label: 'File', name: 'file', widget: 'file', required: false} # new
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'world-and-setting' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'World & Setting' # Used in the UI, ie.: "New Post"
    label_singular: 'World & Setting Page'
    folder: 'content/lore/2-world-and-setting' # The path to the folder where the documents are stored
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: true
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Intro Blurb", name: "description", widget: "text"} # new
      - {label: "Image", name: "image", widget: "image", required: false} # new
      - { label: 'File', name: 'file', widget: 'file', required: false} # new
      - { label: 'Body', name: 'body', widget: 'markdown' } # new


  - name: 'locations' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Locations' # Used in the UI, ie.: "New Post"
    label_singular: 'Locations Page'
    folder: 'content/lore/3-locations' # The path to the folder where the documents are stored
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: true
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Intro Blurb", name: "description", widget: "text"} # new
      - {label: "Image", name: "image", widget: "image", required: false} # new
      - { label: 'File', name: 'file', widget: 'file', required: false} # new
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'factions' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Factions' # Used in the UI, ie.: "New Post"
    label_singular: 'Factions Page'
    folder: 'content/lore/4-factions' # The path to the folder where the documents are stored
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: true
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Intro Blurb", name: "description", widget: "text"} # new
      - {label: "Image", name: "image", widget: "image", required: false} # new
      - { label: 'File', name: 'file', widget: 'file', required: false} # new
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'character-creation' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Character Creation' # Used in the UI, ie.: "New Post"
    label_singular: 'Character Creation Page'
    folder: 'content/lore/5-character-creation' # The path to the folder where the documents are stored
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: true
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Intro Blurb", name: "description", widget: "text"} # new
      - {label: "Image", name: "image", widget: "image", required: false} # new
      - { label: 'File', name: 'file', widget: 'file', required: false} # new
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'roleplay' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Roleplay' # Used in the UI, ie.: "New Post"
    label_singular: 'Roleplay Page'
    folder: 'content/lore/6-roleplay' # The path to the folder where the documents are stored
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: true
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {label: "Intro Blurb", name: "description", widget: "text"} # new
      - {label: "Image", name: "image", widget: "image", required: false} # new
      - { label: 'File', name: 'file', widget: 'file', required: false} # new
      - { label: 'Body', name: 'body', widget: 'markdown' }


  # hacks - upload .yaml to /data/idcard
  - name: 'upload-idcard' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'upload-idcard' # Used in the UI, ie.: "New Post"
    label_singular: 'upload-idcard'
    folder: 'data/idcard' # The path to the folder where the documents are stored
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: false
    extension: yaml
    format: yaml
    fields: # The fields each document in this collection have
      - { label: 'File', name: 'file', widget: 'file', required: false} # new
      - { label: 'Content', name: 'body', widget: 'code' }